name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Init submodules
        uses: snickerbockers/submodules-init@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.25'

      - name: Install system deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq libgtest-dev \
            libsdl1.2-dev \
            libboost-all-dev \
            libgl1-mesa-dev libglu1-mesa-dev \
            libglew-dev \
            libvorbis-dev \
            zlib1g-dev \
            libfreetype6-dev \
            gettext

      - name: Configure CMake
        run: |
          cmake -S . -B build

      - name: Build
        run: |
          cmake --build build -- -j

      - name: Run tests
        run: build/unittests
