name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Init submodules
        uses: snickerbockers/submodules-init@v4

      # Restore APT cache
      - name: Restore APT cache
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-${{ hashFiles('apt-deps.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Download system deps
        run: |
          sudo apt-get update
          sudo apt-get install --download-only -y $(cat apt-deps.txt)

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y $(cat apt-deps.txt)

      - name: Configure CMake (export compile commands)
        run: |
          cmake -S . -B build -DRLVM_BUILD_TESTS=ON \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy
        run: |
          run-clang-tidy -p build/ \
          $(find src -iname '*.cpp') \
          -- \
          -std=c++20

      - name: Check formatting with clang-format
        run: |
          find src test -type f \( -o -name '*.hpp' -o -name '*.cpp' \) \
          | xargs clang-format --dry-run --Werror -style=file

  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Init submodules
        uses: snickerbockers/submodules-init@v4

      - name: Restore APT cache
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-${{ hashFiles('apt-deps.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      # Download & Install
      - name: Download system deps
        run: |
          sudo apt-get update
          sudo apt-get install --download-only -y $(cat apt-deps.txt)

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y $(cat apt-deps.txt)

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.25'

      - name: Configure CMake
        run: |
          cmake -S . -B build -DRLVM_BUILD_TESTS=ON

      - name: Build & Run tests
        run: |
          cmake --build build --target run_tests -- -j$(nproc)
